# Generated by Django 2.2 on 2019-05-16 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telebe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=80, verbose_name='adi')),
                ('soyad', models.CharField(max_length=80, verbose_name='soyad')),
                ('ata', models.CharField(max_length=80, verbose_name='ata adi')),
                ('fakulte', models.CharField(max_length=80, verbose_name='fakulte')),
                ('ixtsas', models.CharField(max_length=80, verbose_name='ixtisas')),
                ('grup', models.CharField(max_length=80, verbose_name='grup')),
                ('melumat', models.TextField(blank=True, verbose_name='melumat')),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='Tarix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publish', 'id'],
            },
        ),
    ]
