# Generated by Django 2.2 on 2019-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telebe',
            name='ay',
            field=models.CharField(choices=[('yanvar', 'yanvar'), ('fevral', 'fevral'), ('mart', 'mart'), ('aprel', 'aprel'), ('may', 'may'), ('iyun', 'iyun'), ('iyul', 'iyul'), ('avgust', 'avgust'), ('sentyabr', 'sentyabr'), ('oktyabr', 'oktyabr'), ('noyabr', 'noyabr'), ('dekabr', 'dekabr')], default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telebe',
            name='doguldugu',
            field=models.CharField(default=1, max_length=80, verbose_name='doguldugu yer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telebe',
            name='gun',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=1, max_length=80),
            preserve_default=False,
        ),
    ]
